spring:
  data:
    rest:
      base-path: /api/v1
  datasource:
    url: jdbc:h2:mem:marvel;IGNORECASE=TRUE
    username: marvel
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
springdoc:
  swagger-ui:
    enabled: true
  use-management-port: true
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

marvelService:
  marvelExternalApi:
    url: http://gateway.marvel.com
    path: /v1/public
    publicKey: ${MARVEL_PUBLIC_KEY}
    privateKey: ${MARVEL_PRIVATE_KEY}
