spring:
  datasource:
    url: jdbc:h2:mem:marvel;IGNORECASE=TRUE
    username: marvel
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect